pull_request_rules:
  - name: automatic merge
    conditions:
      - label!=DNM
      - '#approved-reviews-by>=1'
      - 'status-success=ci/circleci'
      - 'status-success=continuous-integration/travis-ci/pr'
      - 'status-success=DCO'
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: smart
      dismiss_reviews: {}
      delete_head_branch: {}
